---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

    ## Database
    - { role: mysql }

    ## Scripting / Language support
    - { role: php-fpm, root_directory: "{{ web_directory }}", nginx_site_template: "symfony4-site.j2" }

    ## Install Gulp with Drifter Gulpfile in the box
    # - { role: gulp }

    ## Install Elasticsearch in the box
    # - { role: elasticsearch }

    ## Install Composer in the box
    - { role: composer }

    # If you want php xdebug in your local boxes, uncomment this
    # The when clause prevents it to be installed on the CI_SERVER
    # - { role: php-xdebug, when: "'{{ lookup('env','CI_SERVER') }}' != 'yes'" }

    ## Install the ssh rule, installs gitlab.liip.ch and github.com host key
    - { role: ssh }

    ## You can also creates your own role, just add a directory under the 'virtualization'
    ## folder and refer to it like for other roles :
    # - { role: my_own_role }

# If needed, you can specify your own tasks
  tasks:
    - name: install project dependencies
      shell: cd {{ root_directory }} && composer.phar --quiet install
